-- migrate:up
create schema if not exists config;

create table if not exists config.social_app_type
(
    social_app_type  text not null primary key
);

create table if not exists config.social_app
(
    app_id                      bigint  not null generated by default as identity,
    social_app_type             text not null,
    client_id                   text not null,
    secret                      text not null,
    callback_url                text,
    primary key (app_id),
    foreign key (social_app_type) references config.social_app_type(social_app_type) ON DELETE CASCADE
);


create unique index social_app__type on config.social_app (social_app_type);

create table if not exists config.user_social
(
    user_social_id              bigint not null generated by default as identity primary  key,
    app_id                      bigint not null,
    user_id                     text not null,
    meta_data                   jsonb,
    access_token                text,
    secret_token                text,
    foreign key(app_id) references config.social_app(app_id)
);

-- migrate:down
drop table if exists  config.user_social;
drop table if exists  config.social_app;
drop table if exists config.social_app_type;

drop schema if exists config; 
