kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: geekbeacon/socialsvc
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
