version: "3.8"
services:
  socialsvc:
    build:
      context: .
    image: geekbeacon/social-api:latest
    volumes:
        - ./conf:/opt/gb-svc-social-api/conf/
    ports:
      - 8011:8011
  social_db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    env_file: .env
