version: '3.7'

services:
  social_www:
      image: geekbeacon/social-api:latest
      build: social-api
      command:  --server.port=2020 --spring.database.url=jdbc:postgresql://db:5432/social
      env_file: .env
      ports:
        - 9020:2020
  migrate:
    image: flyway/flyway:6.5.5
    command: -configFiles=conf/docker.conf migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    env_file: .env
    depends_on:
      - social_db

  social_db:
    image: postgres:12
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    env_file: .env
