version: '3.7'

services:
  www:
    image: nginx:latest
    volumes:
      - ./static/:/usr/share/nginx/html:ro
    restart: always
    ports:
      - 9999:80
  social_db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    env_file: .env
