version: '3.7'

services:
  social_www:
      image: geekbeacon/social-api:latest
      build: social-api
      command:  --server.port=2020 --spring.database.url=jdbc:postgresql://db:5432/social
      env_file: .env
      ports:
        - 9000:2020
  social_db:
    image: postgres:11.5
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    env_file: .env
