version: '2.1'

services:
  db:
    image: postgres:11.5
    restart: always
    env_file: .env
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
