SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: config; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA config;


--
-- Name: nixie; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA nixie;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: social_app; Type: TABLE; Schema: config; Owner: -
--

CREATE TABLE config.social_app (
    app_id bigint NOT NULL,
    social_app_type text NOT NULL,
    client_id text NOT NULL,
    secret text NOT NULL,
    callback_url text
);


--
-- Name: social_app_app_id_seq; Type: SEQUENCE; Schema: config; Owner: -
--

ALTER TABLE config.social_app ALTER COLUMN app_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME config.social_app_app_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_app_type; Type: TABLE; Schema: config; Owner: -
--

CREATE TABLE config.social_app_type (
    social_app_type text NOT NULL
);


--
-- Name: user_social; Type: TABLE; Schema: config; Owner: -
--

CREATE TABLE config.user_social (
    user_social_id bigint NOT NULL,
    app_id bigint NOT NULL,
    user_id text NOT NULL,
    meta_data jsonb,
    access_token text,
    secret_token text
);


--
-- Name: user_social_user_social_id_seq; Type: SEQUENCE; Schema: config; Owner: -
--

ALTER TABLE config.user_social ALTER COLUMN user_social_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME config.user_social_user_social_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: contact_form; Type: TABLE; Schema: nixie; Owner: -
--

CREATE TABLE nixie.contact_form (
    contact_form_id bigint NOT NULL,
    email text NOT NULL,
    description text NOT NULL,
    domain text DEFAULT 'nixiepixel.com'::text NOT NULL
);


--
-- Name: contact_form_contact_form_id_seq; Type: SEQUENCE; Schema: nixie; Owner: -
--

ALTER TABLE nixie.contact_form ALTER COLUMN contact_form_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME nixie.contact_form_contact_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying(255) NOT NULL
);


--
-- Name: social_app social_app_pkey; Type: CONSTRAINT; Schema: config; Owner: -
--

ALTER TABLE ONLY config.social_app
    ADD CONSTRAINT social_app_pkey PRIMARY KEY (app_id);


--
-- Name: social_app_type social_app_type_pkey; Type: CONSTRAINT; Schema: config; Owner: -
--

ALTER TABLE ONLY config.social_app_type
    ADD CONSTRAINT social_app_type_pkey PRIMARY KEY (social_app_type);


--
-- Name: user_social user_social_pkey; Type: CONSTRAINT; Schema: config; Owner: -
--

ALTER TABLE ONLY config.user_social
    ADD CONSTRAINT user_social_pkey PRIMARY KEY (user_social_id);


--
-- Name: contact_form contact_form_pkey; Type: CONSTRAINT; Schema: nixie; Owner: -
--

ALTER TABLE ONLY nixie.contact_form
    ADD CONSTRAINT contact_form_pkey PRIMARY KEY (contact_form_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: social_app__type; Type: INDEX; Schema: config; Owner: -
--

CREATE UNIQUE INDEX social_app__type ON config.social_app USING btree (social_app_type);


--
-- Name: social_app social_app_social_app_type_fkey; Type: FK CONSTRAINT; Schema: config; Owner: -
--

ALTER TABLE ONLY config.social_app
    ADD CONSTRAINT social_app_social_app_type_fkey FOREIGN KEY (social_app_type) REFERENCES config.social_app_type(social_app_type) ON DELETE CASCADE;


--
-- Name: user_social user_social_app_id_fkey; Type: FK CONSTRAINT; Schema: config; Owner: -
--

ALTER TABLE ONLY config.user_social
    ADD CONSTRAINT user_social_app_id_fkey FOREIGN KEY (app_id) REFERENCES config.social_app(app_id);


--
-- PostgreSQL database dump complete
--


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20200523225950'),
    ('20200523230103'),
    ('20200523231124');
