output = "dbmodels/config/models"
wipe = true
no-tests = true

[psql]
dbname = "socialdb"
host   = "localhost"
port   = 5432
user   = "postgres"
pass   = "secret"
schema = "config"
sslmode = "disable"

