// Code generated by SQLBoiler 4.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	SocialApp     string
	SocialAppType string
	UserSocial    string
}{
	SocialApp:     "social_app",
	SocialAppType: "social_app_type",
	UserSocial:    "user_social",
}
