debug: true

logging:
  pattern:
    console: '%msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%'
  level:
    org:
      springframework: ERROR
    root: INFO

spring:
  datasource:
    #    url: jdbc:postgresql://localhost:5432/social
    url: jdbc:postgresql://192.168.99.102:5432/social
    username: social
    password: social